# Generated by Django 4.1.1 on 2022-11-20 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='letter',
            new_name='Letters',
        ),
    ]
